name: CI on a PR to the develop branch

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS v18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Start lint
        run: npx nx affected --target=lint
      - name: Start build
        run: npx nx affected --target=build --base=origin/develop
      - name: Start Unit tests
        run: npx nx affected --target=test --base=origin/develop
