name: CI on a PR to the develop branch

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Validate branch name
        run: |
          if [[ ${{ github.head_ref }} =~ ^(feature|bugfix|test)/.*$ ]]; then
            echo "Branch name is valid"
          else
            echo "Invalid branch name. Please use 'feature/<name>', 'bugfix/<name>' or 'test/<name>' format"
            exit 1
          fi

  build:
    needs: validate-branch-name
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use NodeJS v18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Start lint
        run: npx nx affected --target=lint --base=origin/develop
      - name: Start build
        run: npx nx affected --target=build --base=origin/develop
      - name: Start Unit tests
        run: npx nx affected --target=test --base=origin/develop
